### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by tamsky** [globeandmail/ansible-role-amazon-cloudwatch-agent#1]
This request extends to all of globeandmail's ansible-role-* repos that lack a documented LICENSE.

- ansible-role-apt-cron
- ansible-role-nginx
- ansible-role-rpcbind
- ansible-role-nis
- ansible-role-postfix
- ansible-role-ntp
- ansible-role-nrpe
- ansible-role-sysstat
- ansible-role-motd
- ansible-role-newrelic-java-agent

thanks!

**Comment by OnlyLoveOleg** [comment]
@tamsky thanks for the heads up. Should be resolved now :)
